# Generated by Django 4.2.23 on 2026-06-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmsuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hmsuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
