# Generated by Django 4.2.23 on 2026-06-07 03:45

from django.db import migrations

def seed_departments(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    departments = [
        {'name': 'Cardiology', 'description': 'Cardiovascular medicine and surgery'},
        {'name': 'Neurology', 'description': 'Brain and nervous system treatment'},
        {'name': 'Pediatrics', 'description': 'Medical care of infants, children, and adolescents'},
        {'name': 'Orthopedics', 'description': 'Skeletal and muscular system treatment'},
        {'name': 'General Medicine', 'description': 'General health and primary clinical care'},
        {'name': 'Emergency', 'description': '24/7 urgent medical response services'},
    ]
    for dept in departments:
        Department.objects.get_or_create(name=dept['name'], defaults={'description': dept['description']})

def reverse_seed_departments(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    names = ['Cardiology', 'Neurology', 'Pediatrics', 'Orthopedics', 'General Medicine', 'Emergency']
    Department.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hmsuser_employee_id_hmsuser_phone'),
    ]

    operations = [
        migrations.RunPython(seed_departments, reverse_code=reverse_seed_departments),
    ]
