# Generated by Django 4.2.23 on 2026-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctorapplication_staffinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmsuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('RADIOLOGIST', 'Radiologist'), ('PATIENT', 'Patient')], default='DOCTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('RADIOLOGIST', 'Radiologist'), ('PATIENT', 'Patient')], default='DOCTOR', max_length=20),
        ),
    ]
