# Generated by Django 5.2.14 on 2026-06-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hmsuser_cnic_hmsuser_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
