# Generated by Django 5.2.14 on 2026-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_prescriptiondispense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptiondispense',
            name='medical_record',
        ),
        migrations.RemoveField(
            model_name='prescriptiondispense',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='PrescriptionDispense',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
