# Generated by Django 5.2.14 on 2026-06-13 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_invoice_appointment_and_more'),
        ('departments', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinvite',
            name='department',
        ),
        migrations.AlterField(
            model_name='hmsuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.department'),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorApplication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffInvite',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
