# Generated by Django 5.2.14 on 2026-06-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_staffinvite_department_and_more'),
        ('billing', '0002_invoice_due_date_invoice_insurance_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
