# Generated by Django 5.2.14 on 2026-06-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmsuser',
            name='cross_authorized_roles',
            field=models.CharField(blank=True, default='', help_text="Comma-separated list of secondary/cross-authorized roles (e.g. 'PHARMACIST,LAB_TECHNICIAN')", max_length=255),
        ),
    ]
