# Roles
ROLE_ADMIN = 'ADMIN'
ROLE_DOCTOR = 'DOCTOR'
ROLE_NURSE = 'NURSE'
ROLE_RECEPTIONIST = 'RECEPTIONIST'
ROLE_PHARMACIST = 'PHARMACIST'
ROLE_LAB_TECHNICIAN = 'LAB_TECHNICIAN'
ROLE_RADIOLOGIST = 'RADIOLOGIST'
ROLE_PATIENT = 'PATIENT'

CLINICAL_ROLES = (ROLE_DOCTOR, ROLE_NURSE, ROLE_LAB_TECHNICIAN, ROLE_RADIOLOGIST)
STAFF_ROLES = (ROLE_ADMIN, ROLE_DOCTOR, ROLE_NURSE, ROLE_RECEPTIONIST, ROLE_PHARMACIST, ROLE_LAB_TECHNICIAN, ROLE_RADIOLOGIST)

# Appointment Statuses
APPT_STATUS_PENDING = 'PENDING'
APPT_STATUS_CONFIRMED = 'CONFIRMED'
APPT_STATUS_COMPLETED = 'COMPLETED'
APPT_STATUS_CANCELLED = 'CANCELLED'

# Invoice Statuses
INVOICE_STATUS_PENDING = 'PENDING'
INVOICE_STATUS_PARTIAL = 'PARTIAL'
INVOICE_STATUS_PAID = 'PAID'
INVOICE_STATUS_OVERDUE = 'OVERDUE'
INVOICE_STATUS_CANCELLED = 'CANCELLED'
