# Generated by Django 5.2.14 on 2026-06-13 04:07

import django.db.models.deletion
from django.db import migrations, models


def populate_paid_amount(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    for invoice in Invoice.objects.all():
        if invoice.payment_status == 'PAID':
            invoice.paid_amount = invoice.amount
            invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='insurance_provider',
            field=models.CharField(blank=True, choices=[('SEHAT_CARD', 'Sehat Sahulat Card'), ('STATE_LIFE', 'State Life Insurance'), ('JUBILEE', 'Jubilee Life Insurance'), ('EFU', 'EFU General Insurance'), ('ASKARI', 'Askari General Insurance'), ('TPL', 'TPL Insurance'), ('OTHER', 'Other Panel / Insurance')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_PAY', 'Mobile Pay'), ('INSURANCE', 'Insurance'), ('MIXED', 'Mixed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.RunPython(populate_paid_amount),
    ]
