# Generated by Django 5.2.14 on 2026-06-13 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('pmdc_expiry_date', models.DateField(blank=True, help_text='Expiry date of PMDC registration', null=True)),
                ('license_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING_RENEWAL', 'Pending Renewal')], default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_doctor',
            },
        ),
    ]
