# Generated by Django 5.2.14 on 2026-06-13 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('pmdc_number', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('current_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('pmdc_certificate', models.FileField(upload_to='doctor_applications/certificates/')),
                ('cnic_document', models.FileField(upload_to='doctor_applications/cnic/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_doctorapplication',
            },
        ),
    ]
