# Generated by Django 5.2.14 on 2026-06-13 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '__first__'),
        ('doctors', '0001_initial'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Under Cleaning'), ('MAINTENANCE', 'Out of Service')], default='AVAILABLE', max_length=20)),
            ],
            options={
                'db_table': 'ipd_bed',
            },
        ),
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('admission_reason', models.TextField()),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged')], default='ADMITTED', max_length=20)),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admitted_patients', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ipd.bed')),
            ],
            options={
                'db_table': 'ipd_admissionrecord',
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General Ward'), ('PRIVATE', 'Private Room'), ('ICU', 'Intensive Care Unit'), ('CCU', 'Coronary Care Unit')], default='GENERAL', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='departments.department')),
            ],
            options={
                'db_table': 'ipd_ward',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='ipd.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
